name: Deploy to Firebase Hosting on New Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.FIREBASE_CREDENTIALS }} > src/credentails.js
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIELAND_D92B1 }}'
          projectId: movieland-d92b1
